;; -*- coding: utf-8; lexical-binding: t; -*-
;;; Code:
(autoload 'xclip-set-selection "xclip" "" t)
(autoload 'xclip-get-selection "xclip" "" t)
(autoload 'dianyou-group-make-nnir-group "dianyou" "" t)
(autoload 'dianyou-summary-extract-email-address "dianyou" "" t)
(autoload 'dianyou-switch-gnus-buffer "dianyou" "" t)
(autoload 'dianyou-insert-email-address-from-received-mails "dianyou" "" t)
(autoload 'dianyou-paste-image-from-clipboard "dianyou" "" t)
(autoload 'gmail2bbdb-import-file "gmail2bbdb" "" t)
(autoload 'mybigword-show-big-words-from-file "mybigword" "" t)
(autoload 'mybigword-show-big-words-from-current-buffer "mybigword" "" t)
(autoload 'mybigword-play-video-of-word-at-point "mybigword" "" t)
(autoload 'mybigword-pronounce-word "mybigword" "" t)
(autoload 'js2hl-show-thing-at-point "js2hl" "" t)
(autoload 'js2hl-show-exits "js2hl" "" t)
(autoload 'js2hl-rename-thing-at-point "js2hl" "" t)

;; (autoload 'workgroups-mode "workgroups2" nil t)
;; (autoload 'wg-create-workgroup "workgroups2" nil t)
;; (autoload 'wg-open-workgroup "workgroups2" nil t)
(autoload 'csv-nav-mode "csv-nav-mode" "Major mode for navigating comma-separated value files." t)
(autoload 'counsel-etags-find-tag-at-point "counsel-etags" "" t nil)
(autoload 'counsel-etags-list-tag-in-current-file "counsel-etags" "" t nil)
(autoload 'counsel-etags-push-marker-stack "counsel-etags" "" t nil)
(autoload 'sdcv-search-pointer "sdcv" "show word explanation in buffer" t)
(autoload 'sdcv-search-input+ "sdcv" "show word explanation in tooltip" t)
(autoload 'sdcv-search-input "sdcv" "show word explanation in tooltip" t)
;; (autoload 'org2nikola-export-subtree "org2nikola" "" t)
;; (autoload 'org2nikola-rerender-published-posts "org2nikola" "" t)
(autoload 'dictionary-new-search "dictionary" "" t nil)
;; (autoload 'legalese "legalese" "" t)
(autoload 'popup-tip "popup")
;; (autoload 'srt-renumber-subtitles "subtitles" "" t)
;; (autoload 'srt-offset-subtitles "subtitles" "" t)
;; (autoload 'srt-mult-subtitles "subtitles" "" t)
;; (autoload 'srt-convert-sub-to-srt "subtitles" "" t)
;; (autoload 'fastdef-insert "fastdef" nil t)
;; (autoload 'fastdef-insert-from-history "fastdef" nil t)
(autoload 'doctest-mode "doctest-mode" "Python doctest editing mode." t)
(autoload 'find-library-name "find-func")
(autoload 'run-js "js-comint" "")
(autoload 'vc-msg-show "vc-msg" "")
(autoload 'gtags-mode "gtags" "" t)

(autoload 'dropdown-list "dropdown-list")

(provide 'init-autoload)
;;; init-autoload.el ends here
